_BASE_: ./configs/pyramid.yaml

CONFIG:
    DATA_NAME: CIFAR100
    MODEL_NAME: PYRAMIDNET
    DEPTH: 200
    ALPHA: 240

    CONV_BIAS: False

    DROPOUT_TYPE: NONE
    DROPOUT_RATIO: 0

    RECONSTRUCT: False
    RECONSTRUCT_MSE_LOSS: False
    RECONSTRUCT_CE_LOSS: False